from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[1]

SAMPLE_RATE = 22050
N_MELS = 80
N_FFT = 1024
HOP_LENGTH = 256
WIN_LENGTH = 1024

PAD_TOKEN_ID = 0
UNKNOWN_TOKEN_ID = 1
VOCAB_SIZE = 11256

EMBEDDING_DIM = 128
ENCODER_DIM = 256
DECODER_DIM = 256

CHECKPOINT_DIR = BASE_DIR / "checkpoints"
FEMALE_CHECKPOINT_PATH = CHECKPOINT_DIR / "social_story_5000.pt"
MALE_CHECKPOINT_PATH = CHECKPOINT_DIR / "male_tts.pt"
